#!/bin/bash

check_boot_files () {
    for file in "$@"; do
        if [[ ! -f "${file}" ]]; then
            return 1
        fi
    done
    return 0
}

# Per the QEMU documentation, this machine is used with this version of the
# system emulator
qemu_emulator=qemu-system-aarch64
machine=xilinx-zynq-a9

proj_dir="$(realpath -e ./)"
rootfs_dir="${proj_dir}/rootfs"

dtb_path="${rootfs_dir}/boot/zynq-zc702.dtb"
kernel_path="${rootfs_dir}/boot/zImage"
initrd_path="${proj_dir}/initramfs.cpio.gz"

# Kernel command line arguments - don't disable fabric clocks that don't have a
# drivers
kernel_cmd_line=""
# Basic options here
kernel_cmd_line+=" console=ttyPS0,115200"
# Tells the kernel to not disable clocks that are referenced by a device tree
# entry
kernel_cmd_line+=" clk_ignore_unused"

if [[ "${1}" == '--quiet' ]]; then
    kernel_cmd_line+=" quiet"
fi

# Do some basic checks of the environment and boot components before we
# invoke the emulator
command -v "${qemu_emulator}" >/dev/null 2>&1 || \
    { printf '%s\n' "Error: QEMU emulator for ARM not installed" >&2; exit 1; }

check_boot_files "${dtb_path}" "${kernel_path}" "${initrd_path}" || \
    { printf '%s\n' "Error: Missing boot files" >&2; exit 1; }

# From the QEMU system emulation documentation, the general form of calling the
# emulator is
#
# $ qemu-system-x86_64 [machine opts] \
#                 [cpu opts] \
#                 [accelerator opts] \
#                 [device opts] \
#                 [backend opts] \
#                 [interface opts] \
#                 [boot opts]
#
"${qemu_emulator}" \
    -machine type="${machine}" \
    -accel tcg \
    -dtb "${dtb_path}" \
    -serial null \
    -serial stdio \
    -monitor telnet:127.0.0.1:55555,server,nowait \
    -display none \
    -initrd "${initrd_path}" \
    -kernel "${kernel_path}" \
    -append "${kernel_cmd_line}" \
    -net nic -net user,hostfwd=udp::6666-:6666 \
    -m 2048M

