BUSYBOX_SRC_URL		:= https://github.com/mirror/busybox.git
BUSYBOX_SRC_TAG		:= 1_36_1
BUSYBOX_SRC_DIR		:= $(EXTERN_DIR)/busybox

BUSYBOX_BUILD_DIR	:= $(BUILD_DIR)/busybox
BUSYBOX_BIN		:= $(BUSYBOX_BUILD_DIR)/busybox

$(BUSYBOX_BIN): $(BUSYBOX_BUILD_DIR)/.config
	$(MAKE) -C $(BUSYBOX_SRC_DIR) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) \
		O=$(BUSYBOX_BUILD_DIR)

$(BUSYBOX_BUILD_DIR)/.config: $(BUSYBOX_SRC_DIR)/Makefile
	@mkdir -p $(@D)
	$(MAKE) -C $(BUSYBOX_SRC_DIR) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) \
		O=$(BUSYBOX_BUILD_DIR) mrproper
	$(MAKE) -C $(BUSYBOX_SRC_DIR) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) \
		O=$(BUSYBOX_BUILD_DIR) defconfig
	$(MAKE) -C $(BUSYBOX_SRC_DIR) ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) \
		O=$(BUSYBOX_BUILD_DIR) menuconfig

$(BUSYBOX_SRC_DIR)/Makefile: $(EXTERN_DIR)
	$(GIT) clone $(GIT_FLAGS) --branch $(BUSYBOX_SRC_TAG) $(BUSYBOX_SRC_URL) $(BUSYBOX_SRC_DIR)

busybox-clean:
	rm -rf $(BUSYBOX_BUILD_DIR)


